replicaCount: 1

image:
  mongo:
    repository: yamakariy/mongodb_coursework
    pullPolicy: Always
    restartPolicy: Always
    app: mongodb
    containerPort: 27017
    env1:
      name: MONGO_INITDB_DATABASE
      value: tchallenge
    env2:
      name: MONGO_INITDB_ROOT_PASSWORD
      value: password
    env3:
      name: MONGO_INITDB_ROOT_USERNAME
      value: admin
  express:
    repository: mongo-express
    pullPolicy: Always
    restartPolicy: Always
    app: mongo-express
    containerPort: 8081
    env1:
      name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: password
    env2:
      name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: admin
    env3:
      name: ME_CONFIG_MONGODB_SERVER
      value: mongodb

service:
  mongo:
    name: "27017"
    type: ClusterIP
    port: 27017
    targetPort: 27017
  express:
    name: "8081"
    type: ClusterIP
    port: 8081
    targetPort: 8081

route:
  express:
    host: mongo-express.openshift.devops.t-systems.ru
    path: /